CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  name TEXT NOT NULL,
  email VARCHAR(254) UNIQUE,
  phone VARCHAR(20) UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'FARMER',
  language VARCHAR(10) NOT NULL DEFAULT 'en',
  location VARCHAR(120),
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  farmer_id INTEGER NOT NULL REFERENCES users(id),
  crop VARCHAR(80) NOT NULL,
  category VARCHAR(80) NOT NULL,
  quantity REAL NOT NULL,
  unit VARCHAR(20) NOT NULL,
  price REAL NOT NULL,
  location VARCHAR(120) NOT NULL,
  available_date VARCHAR(20) NOT NULL,
  image_url VARCHAR(255),
  description TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS verifications (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  farmer_id INTEGER NOT NULL REFERENCES users(id),
  status VARCHAR(40) NOT NULL DEFAULT 'PENDING',
  notes TEXT,
  submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME,
  reviewed_by INTEGER REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS market_prices (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  crop VARCHAR(80) NOT NULL,
  location VARCHAR(120) NOT NULL,
  low REAL NOT NULL,
  average REAL NOT NULL,
  high REAL NOT NULL,
  source VARCHAR(100) NOT NULL DEFAULT 'DEMO DATA',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS buyer_requests (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  product_id INTEGER NOT NULL REFERENCES products(id),
  buyer_id INTEGER NOT NULL REFERENCES users(id),
  message TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  user_id INTEGER NOT NULL REFERENCES users(id),
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER PRIMARY KEY {{AUTO_INCREMENT}},
  actor_id INTEGER REFERENCES users(id),
  action VARCHAR(40) NOT NULL,
  entity VARCHAR(40) NOT NULL,
  entity_id INTEGER,
  details TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
